"""empty message

Revision ID: 16a9a044eaa2
Revises: 
Create Date: 2021-05-24 01:33:41.734701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a9a044eaa2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.UnicodeText(), nullable=True),
    sa.Column('author', sa.UnicodeText(), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('provider', sa.Integer(), nullable=True),
    sa.Column('plays_count', sa.Integer(), nullable=True),
    sa.Column('import_date', sa.DateTime(), nullable=True),
    sa.Column('extra_location_data', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('tag', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('tag')
    )
    op.create_table('association',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['tag'], ['tags.tag'], ),
    sa.PrimaryKeyConstraint('song_id', 'tag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('tags')
    op.drop_table('songs')
    # ### end Alembic commands ###
