"""empty message

Revision ID: d51734556cd7
Revises: 
Create Date: 2021-05-23 06:43:58.153694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd51734556cd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.UnicodeText(), nullable=True),
    sa.Column('author', sa.UnicodeText(), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('provider', sa.Integer(), nullable=True),
    sa.Column('tags', sa.PickleType(), nullable=True),
    sa.Column('plays_count', sa.Integer(), nullable=True),
    sa.Column('import_date', sa.DateTime(), nullable=True),
    sa.Column('extra_location_data', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    # ### end Alembic commands ###
